### ISSUE TITLE
Inline `mime-db` to avoid Artifact and JSON dependency

### ISSUE THREAD

**Issue by fonsp** [fonsp/MIMEs.jl#2]
https://github.com/fonsp/MIMEs.jl/blob/43bf22fe44a60b0483ed6f30aa03d5781e30c85b/README.md?plain=1#L47

Instead of using Artifacts and JSON during package precompilation, we could this ourselves, and publish the parsed MIME database directly in our source code! The assumption is that this will give a performance benefit overall.

**Comment by fonsp** [comment]
@tlienart suggested in https://github.com/JuliaWeb/HTTP.jl/issues/811#issuecomment-1078202598 to combine #1 and #2 into one!

**Comment by tlienart** [comment]
I put this on branch https://github.com/fonsp/MIMEs.jl/tree/tl/mimedb, time to first mime is now pretty small 👍

```julia
julia> @time using MIMEs; mime_from_extension(".js");
  0.078269 seconds (182.53 k allocations: 10.424 MiB, 95.43% compilation time)
```

running the script `mimedb/update.jl` could be done on a chron job with CI (maybe quarterly) it could maybe be made slightly more complex to get the latest DB, check the tests pass and if they do, open a PR against the repo that a maintainer can then just merge. 

note: compare to the current

```julia
julia> @time using MIMEs; mime_from_extension(".js");
  0.483490 seconds (570.64 k allocations: 57.962 MiB, 20.20% gc time, 81.94% compilation time)
```

 note that it looks like @tkf had a similar idea? https://github.com/tkf/MIMEFileExtensions.jl ; similar perfs (actually a wee bit faster) but DB is maybe not as complete (not sure):

```julia
julia> @time using MIMEFileExtensions; mimes_from_fileext("js")
  0.071222 seconds (71.55 k allocations: 4.337 MiB, 70.35% compilation time)
1-element Vector{Symbol}:
 Symbol("application/javascript")
```

we should probably join forces here especially for such a small util module 😋

**Comment by fonsp** [comment]
Awesome!! Thanks Thibault, let's make a PR!

And yes! It was a crazy coincidence that we both made this package in the same week 🤦. I talked with Takafumi on slack already, he is already using his package for another project, and I need the extra mime features like `charset` (which is not in the apache DB), so we decided to keep both for now. We can always revisit later! I also invited Takafumi as collab on this package. 🌟

**Comment by tkf** [comment]
Yeah, it was a race condition that MIMEs.jl and MIMEFileExtensions.jl popped up at the same time :) I wouldn't have created if I noticed MIMEs.jl. We were also just discussing if MIMEs.jl can be moved to JuliaWeb for better discoverability and maintainability.
