### ISSUE TITLE
Add `text/julia` MIME for `.jl`?

### ISSUE THREAD

**Issue by fonsp** [fonsp/MIMEs.jl#4]
Some info in https://github.com/JuliaLang/julia/issues/26947

The MIME itself is not so important, but it is important to set `charset=utf8` when serving julia files.

**Comment by tlienart** [comment]
can be done by adjusting 
https://github.com/fonsp/MIMEs.jl/blob/784c53aaf8f03cd9c76597c0b8cd0be88e7155a3/mimedb/update.jl#L43-L44 

Note: I think the logic with `skip` can be removed, so that the output file (`mimedb.jlon`) is always overwritten.

**Comment by fonsp** [comment]
Thanks! Do you think it is a good idea to add the julia MIME?

**Comment by tlienart** [comment]
I don't see what harm it would do! Getting a more specific mime would seem to me like a good thing and they should implement fallbacks anyway since there's so many weird and super specific mimes :-)
