### ISSUE TITLE
Zulip

### ISSUE THREAD

**Issue by tlienart** [fonsp/MIMEs.jl#5]
Just a note @fonsp I saw your message via email notification but I don't log into Zulip these days and don't have it on my laptop.

In short: I'm supportive of what you want to do but I don't think I'll be able to help in the near future; I'm barely managing to maintain Franklin and developing the upcoming version as it is now 😓 so unfortunately I don't think I'll really be able to help you. But if you open issues on LiveServer with features that you'd need or things you'd like to see there, happy to consider or even give you collab access!

**Comment by fonsp** [comment]
Thanks for the reply! No worries, keep up the good work with Franklin 🌟
